### ISSUE TITLE
Live TV channels and guide import from myth?

### ISSUE THREAD

**Issue by shottothedome** [ta264/Emby.MythTv#10]
Is there a way to not include channels in myth marked not visible? It is bringing in every single tv channel including the channels marked invisible

Thank you

**Comment by ta264** [comment]
I think that should be fixed in 1.0.3.  You might have to refresh the guide data in the emby settings for live tv.

**Comment by shottothedome** [comment]
Thank you this worked when i finally got a chance to test it out today
