### ISSUE TITLE
Live TV - Unable to play with HDHR3-US

### ISSUE THREAD

**Issue by shottothedome** [ta264/Emby.MythTv#11]
Sorry forgot that the mythtv api doesn't allow live tv. I'm assuming this is why it is not working. You can close/delete this unless there is a way to set things up to start recording then tune the now started recording stream a few seconds later. I think this is what kodi does

I've got two HDHR3-us tuners. They are setup for ATSC. They are able to be tuned in the native emby livetv before adding emby.mythtv.dll. They also work fine in mythtv when I test. However, when i try to play them in emby with emby.mythtv (after clearing everything else out of the live tv section), no live tv plays and instead it just freezes on the black screen with the pending video play going in background. I do see the tuner tune the correct channel and go active in the mythweb status. I've attached the quick log i generated and a screenshot of mythweb
![mythtv-emby-tuning](https://user-images.githubusercontent.com/10160928/27994952-f01eab72-6494-11e7-91be-ea633bf192d7.jpg)

[server-63635124730.txt](https://github.com/ta264/Emby.MythTv/files/1133827/server-63635124730.txt)

**Comment by ta264** [comment]
This should work - I added the ability to use live TV in one of the updates. Looking at your log it seems that myth tuned correctly and sent a file name to emby but emby couldn't read it. Is emby on the same machine as mythtv?  If so it could be a permissions issue. 

I'm about to release a new version, if it doesn't work still then send and up to date log and I'll try to take a look.
