### ISSUE TITLE
No channel icons and series pictures/banners

### ISSUE THREAD

**Issue by shottothedome** [ta264/Emby.MythTv#12]
Clearing everything out of the emby live tv section then adding the emby.mythtv.dll while bringing in the channel guide and series from myth does not bring in all the pretty stuff like channel icons/tv shows banners/images that emby normally has. Is there a way to get channel icons and show pictures/banners?

From messing around with things, it seems like before i add emby.mythtv.dll i can add a normal hdhomerun tuner, then add schedules direct guide listing to map the channels. Run the guide refresh, then after that, remove the tuner and then load emby.mythtv to retain everything. Not sure if it will cause issues/work correctly or not.

**Comment by ta264** [comment]
It's been a while but if you still care the icons will be fetched as they are in mythtv.  The newly added option to grab images from schedules direct should pull in some pretty images. Both of these rely in everything being set up properly in mythtv so make sure you have icons in mythtv and schedules direct ids for programs in your mythtv guide
