### ISSUE TITLE
Recorded Show only one item, with incorrect title

### ISSUE THREAD

**Issue by bmsleight** [ta264/Emby.MythTv#17]
Great plugin!

Running a few virtual machines:-
_mythtv,lan_
Runs mythtv-backend   2:0.27.0+fixes.20140324.8ee257c-0ubuntu3 amd64 Personal video recorder application (server)

_mediaserver.lan_
Runs emby - Version 3.2.60.0
With plugin MythTV 1.0.0.0

Have the schedule recording listed:-
![scheduled](https://user-images.githubusercontent.com/3758389/34921153-28f0086c-f976-11e7-8c6b-c3504962328d.png)

The recorded programs, via mythweb:-
![top](https://user-images.githubusercontent.com/3758389/34921099-69dedb1a-f975-11e7-96bc-85ad8619da8b.png)

More via via mythweb, note the last one of many is "Jamie Johnson"
![bottom](https://user-images.githubusercontent.com/3758389/34921103-76087338-f975-11e7-8288-4eb899dd3172.png)

I have however only one listed recording in Emby. The description is correct, but the title is as per the first recording. It plays ok - the recorded video matched the description/last record program.  
![recorded](https://user-images.githubusercontent.com/3758389/34921158-42c075e2-f976-11e7-9851-495a4b73e8f1.png)

My myth-version may be a little old ?

Regards,
Brendan

**Comment by ta264** [comment]
It's only really been tested with 0.28 (when I used that) and 29 so it may just not work properly with 0.27.  Upgrading to 0.28 should also make live tv work so there are benefits to upgrading...

What do you get visiting this url:
http://mythtv.lan:6544/Dvr/GetRecordedList

**Comment by bmsleight** [comment]
When visiting  http://mythtv.lan:6544/Dvr/GetRecordedList

I get this (962K xml)
https://filebin.ca/3oQ2bH0jDT6w/GetRecordedList

**Comment by ta264** [comment]
I guess this might have been fixed in 1.0.6.  Worth trying again if you haven't already?

**Comment by bmsleight** [comment]
Tested with new install of 0.29  - confirmed working, no errors.
Thanks.
