### ISSUE TITLE
Crashes Emby when attempting to Chromecast

### ISSUE THREAD

**Issue by Crono141** [ta264/Emby.MythTv#19]
The emby server crashes when attempting to cast live tv to a chromecast device.  Log attached.
[embyserver-63666585013.txt](https://github.com/ta264/Emby.MythTv/files/2173138/embyserver-63666585013.txt)

**Comment by ta264** [comment]
Hopefully this is fixed in 1.0.7.  Please can you try that version?

**Comment by Crono141** [comment]
Appears fixed now.  Thanks!
