### ISSUE TITLE
Plugin not working in latest Emby update

### ISSUE THREAD

**Issue by halimcme** [ta264/Emby.MythTv#21]
Updated Emby and live TV is broken.

Getting this message: System.Collections.Generic.KeyNotFoundException: The given key 'LiveTV' was not present in the dictionary.
Full error message: [https://pastebin.com/mnz6gQBM](https://pastebin.com/mnz6gQBM)

Any ideas?

Thanks.

**Comment by ta264** [comment]
My guess is that the plugin can't work out where live TV recordings are stored.

Please can you go into the mythtv plugin settings and expand the storage groups section and post a screenshot of what's there?

**Comment by benklop** [comment]
I didn't realize that you need to have a separate LiveTV storage group. after creating one, restarting mythbackend, and restarting emby, I was able to get live TV to work. Previously I was encountering this issue as well.

**Comment by ta264** [comment]
That's strange, I thought a LiveTV storage group was compulsory looking at the MythTV code.  Did you delete/rename it in MythTV or was it never set up by default?

**Comment by halimcme** [comment]
I created a LiveTV storage group (using the same /tmp/ path as the default one) and live TV works in Emby now! Thanks for the tip. Live TV playback worked fine in Kodi using the default group, so maybe there is something that can be modified in this plugin to make it work again with the default group?

**Comment by halimcme** [comment]
and the group was never setup by default, although this install dates back a few years, maybe that has changed for new installs in current MythTV code?

**Comment by ta264** [comment]
Can you post the output of `<host>:6544/Myth/GetStorageGroupDirs` with and without the live TV group? If I can see the output without I stand a chance of removing the requirement.

**Comment by halimcme** [comment]
With: https://pastebin.com/zpSfk8jR
Without: https://pastebin.com/urqdbV9y

**Comment by ta264** [comment]
That's very helpful thanks. Will have a go after Christmas.

**Comment by halimcme** [comment]
Thanks for your work on this project, Merry Christmas!

**Comment by ta264** [comment]
https://www.mythtv.org/wiki/Setup_Storage_Directories

The docs say live TV is not required, only default. I'll get this sorted out.

**Comment by ta264** [comment]
Please can you try out this version and let me know if it fixed it for you?
https://github.com/ta264/Emby.MythTv/releases/tag/no-livetv-group

**Comment by halimcme** [comment]
Works great! Thanks!

**Comment by ta264** [comment]
This should be resolved (with a better fix) in 1.0.9
