### ISSUE TITLE
Playing recording in progress

### ISSUE THREAD

**Issue by benklop** [ta264/Emby.MythTv#22]
If I try to play a recording that is in progress, at least from my roku (so transcoding is required), playback eventually halts at however far into the program the recording was when I started watching. 

example:
Show starts recording at 8:00 PM
I start watching at 8:15 PM.
Playback ends at 8:30 after playing about 15 minutes of the program.

Compounding the problem, I can't actually start the recording again and fast forward 15 minutes and just resume watching, because emby doesn't know how long the recording is supposed to be, so it only allows skipping forward a few seconds at a time, which takes a few seconds to happen each time, so it's effectively about as fast as just watching it in realtime.

Is this a limitation in the emby PVR support, or is this due to incomplete support in this plugin?

**Comment by ta264** [comment]
Hopefully this is fixed in [v1.0.8](https://github.com/ta264/Emby.MythTv/releases/tag/v1.0.8).  Please can you give it a go and let me know?

**Comment by benklop** [comment]
i've installed the new update, and so far it seems to be working well. thank you!

**Comment by ta264** [comment]
Thanks for letting me know
