### ISSUE TITLE
Plugin not working on Emby 3.1

### ISSUE THREAD

**Issue by marmay** [ta264/Emby.MythTv#7]
For me, the plugin does not work on Emby 3.1.

Does it work with those patches in the separate branch or is there something else to do? Do I have to take care of anything when upgrading to the new Emby release? Again, I'm glad to help, if there is anything I can do.

**Comment by ta264** [comment]
I think there's one more pitch required I haven't pushed to the branch
which makes everything work again. I'll try to get it merged in this
morning.

**Comment by ta264** [comment]
Can you try 1.0.2 please?

**Comment by marmay** [comment]
Looks like things are back to normal, thanks! This does not necessarily mean that everything works, but the plugin is loaded and basic functionality is back again. If there are other issues, I'll report them separately.
