### ISSUE TITLE
MythTV PIN setting in Emby configuration

### ISSUE THREAD

**Issue by wra3** [ta264/Emby.MythTv#9]
Is there a place to set the PIN in the emby client?  If I set it to the default 0000, then the plugin works, but any other pin seems to fail, and I don't know where to set it in the configuration.

**Comment by ta264** [comment]
I don't think there's any way of setting the PIN at the moment.  I'll take a look at some point but I'm fairly busy at the moment so probably won't get around to it for a month or so.  Feel free to send a pull request though!

**Comment by ta264** [comment]
This should be fixed in 1.0.4.  It no longer uses anything that needs the security pin so should just work.
